name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '24'
          cache: maven

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Run Maven Tests
        run: ./mvnw clean test
